site_name: 42 Infrastructure Notes
site_description: Infrastructure notes from 42 projects

theme:
  name: readthedocs

nav:
  - Home: index.md

  - Preview:
      - Born2beroot: preview/born2beroot.md
      - Inception: preview/inception.md

  - Inception of Things:
      - Overview: iot/index.md
      - Project Guide: iot/subject.md
      - Part 1 — K3s & Vagrant: iot/part1.md
      - Part 2 — K3s & Applications: iot/part2.md
      - Part 3 — K3d & Argo CD: iot/part3.md
      - Bonus — GitLab: iot/bonus.md

  - Review:
      - Review: review/index.md

markdown_extensions:
  - tables
  - fenced_code